export interface Country {
  /** código ISO 3166-1 alpha-2 en minúsculas, usado como seed para el color placeholder */
  id: string
  name: string
}

/**
 * Lista de países reconocidos (ISO 3166-1), nombres en español. Sin colores acá —
 * los colores "bandera" son placeholders derivados en runtime vía hashColorPair(country.id)
 * (ver src/lib/colorHash.ts), así este dataset no necesita curación manual de color.
 */
export const COUNTRIES: Country[] = [
  { id: 'af', name: 'Afganistán' },
  { id: 'za', name: 'Sudáfrica' },
  { id: 'al', name: 'Albania' },
  { id: 'de', name: 'Alemania' },
  { id: 'ad', name: 'Andorra' },
  { id: 'ao', name: 'Angola' },
  { id: 'ag', name: 'Antigua y Barbuda' },
  { id: 'sa', name: 'Arabia Saudita' },
  { id: 'dz', name: 'Argelia' },
  { id: 'ar', name: 'Argentina' },
  { id: 'am', name: 'Armenia' },
  { id: 'au', name: 'Australia' },
  { id: 'at', name: 'Austria' },
  { id: 'az', name: 'Azerbaiyán' },
  { id: 'bs', name: 'Bahamas' },
  { id: 'bh', name: 'Baréin' },
  { id: 'bd', name: 'Bangladés' },
  { id: 'bb', name: 'Barbados' },
  { id: 'be', name: 'Bélgica' },
  { id: 'bz', name: 'Belice' },
  { id: 'bj', name: 'Benín' },
  { id: 'bt', name: 'Bután' },
  { id: 'by', name: 'Bielorrusia' },
  { id: 'bo', name: 'Bolivia' },
  { id: 'ba', name: 'Bosnia y Herzegovina' },
  { id: 'bw', name: 'Botsuana' },
  { id: 'br', name: 'Brasil' },
  { id: 'bn', name: 'Brunéi' },
  { id: 'bg', name: 'Bulgaria' },
  { id: 'bf', name: 'Burkina Faso' },
  { id: 'bi', name: 'Burundi' },
  { id: 'cv', name: 'Cabo Verde' },
  { id: 'kh', name: 'Camboya' },
  { id: 'cm', name: 'Camerún' },
  { id: 'ca', name: 'Canadá' },
  { id: 'qa', name: 'Catar' },
  { id: 'td', name: 'Chad' },
  { id: 'cl', name: 'Chile' },
  { id: 'cn', name: 'China' },
  { id: 'cy', name: 'Chipre' },
  { id: 'co', name: 'Colombia' },
  { id: 'km', name: 'Comoras' },
  { id: 'kp', name: 'Corea del Norte' },
  { id: 'kr', name: 'Corea del Sur' },
  { id: 'ci', name: 'Costa de Marfil' },
  { id: 'cr', name: 'Costa Rica' },
  { id: 'hr', name: 'Croacia' },
  { id: 'cu', name: 'Cuba' },
  { id: 'dk', name: 'Dinamarca' },
  { id: 'dm', name: 'Dominica' },
  { id: 'ec', name: 'Ecuador' },
  { id: 'eg', name: 'Egipto' },
  { id: 'sv', name: 'El Salvador' },
  { id: 'ae', name: 'Emiratos Árabes Unidos' },
  { id: 'er', name: 'Eritrea' },
  { id: 'sk', name: 'Eslovaquia' },
  { id: 'si', name: 'Eslovenia' },
  { id: 'es', name: 'España' },
  { id: 'us', name: 'Estados Unidos' },
  { id: 'ee', name: 'Estonia' },
  { id: 'sz', name: 'Esuatini' },
  { id: 'et', name: 'Etiopía' },
  { id: 'ph', name: 'Filipinas' },
  { id: 'fi', name: 'Finlandia' },
  { id: 'fj', name: 'Fiyi' },
  { id: 'fr', name: 'Francia' },
  { id: 'ga', name: 'Gabón' },
  { id: 'gm', name: 'Gambia' },
  { id: 'ge', name: 'Georgia' },
  { id: 'gh', name: 'Ghana' },
  { id: 'gd', name: 'Granada' },
  { id: 'gr', name: 'Grecia' },
  { id: 'gt', name: 'Guatemala' },
  { id: 'gy', name: 'Guyana' },
  { id: 'gn', name: 'Guinea' },
  { id: 'gq', name: 'Guinea Ecuatorial' },
  { id: 'gw', name: 'Guinea-Bisáu' },
  { id: 'ht', name: 'Haití' },
  { id: 'hn', name: 'Honduras' },
  { id: 'hu', name: 'Hungría' },
  { id: 'in', name: 'India' },
  { id: 'id', name: 'Indonesia' },
  { id: 'iq', name: 'Irak' },
  { id: 'ir', name: 'Irán' },
  { id: 'ie', name: 'Irlanda' },
  { id: 'is', name: 'Islandia' },
  { id: 'sb', name: 'Islas Salomón' },
  { id: 'il', name: 'Israel' },
  { id: 'it', name: 'Italia' },
  { id: 'jm', name: 'Jamaica' },
  { id: 'jp', name: 'Japón' },
  { id: 'jo', name: 'Jordania' },
  { id: 'kz', name: 'Kazajistán' },
  { id: 'ke', name: 'Kenia' },
  { id: 'kg', name: 'Kirguistán' },
  { id: 'ki', name: 'Kiribati' },
  { id: 'kw', name: 'Kuwait' },
  { id: 'la', name: 'Laos' },
  { id: 'ls', name: 'Lesoto' },
  { id: 'lv', name: 'Letonia' },
  { id: 'lb', name: 'Líbano' },
  { id: 'lr', name: 'Liberia' },
  { id: 'ly', name: 'Libia' },
  { id: 'li', name: 'Liechtenstein' },
  { id: 'lt', name: 'Lituania' },
  { id: 'lu', name: 'Luxemburgo' },
  { id: 'mk', name: 'Macedonia del Norte' },
  { id: 'mg', name: 'Madagascar' },
  { id: 'my', name: 'Malasia' },
  { id: 'mw', name: 'Malaui' },
  { id: 'mv', name: 'Maldivas' },
  { id: 'ml', name: 'Malí' },
  { id: 'mt', name: 'Malta' },
  { id: 'ma', name: 'Marruecos' },
  { id: 'mh', name: 'Islas Marshall' },
  { id: 'mu', name: 'Mauricio' },
  { id: 'mr', name: 'Mauritania' },
  { id: 'mx', name: 'México' },
  { id: 'fm', name: 'Micronesia' },
  { id: 'md', name: 'Moldavia' },
  { id: 'mc', name: 'Mónaco' },
  { id: 'mn', name: 'Mongolia' },
  { id: 'me', name: 'Montenegro' },
  { id: 'mz', name: 'Mozambique' },
  { id: 'mm', name: 'Myanmar' },
  { id: 'na', name: 'Namibia' },
  { id: 'nr', name: 'Nauru' },
  { id: 'np', name: 'Nepal' },
  { id: 'ni', name: 'Nicaragua' },
  { id: 'ne', name: 'Níger' },
  { id: 'ng', name: 'Nigeria' },
  { id: 'no', name: 'Noruega' },
  { id: 'nz', name: 'Nueva Zelanda' },
  { id: 'om', name: 'Omán' },
  { id: 'nl', name: 'Países Bajos' },
  { id: 'pk', name: 'Pakistán' },
  { id: 'pw', name: 'Palaos' },
  { id: 'pa', name: 'Panamá' },
  { id: 'pg', name: 'Papúa Nueva Guinea' },
  { id: 'py', name: 'Paraguay' },
  { id: 'pe', name: 'Perú' },
  { id: 'pl', name: 'Polonia' },
  { id: 'pt', name: 'Portugal' },
  { id: 'gb', name: 'Reino Unido' },
  { id: 'cf', name: 'República Centroafricana' },
  { id: 'cz', name: 'República Checa' },
  { id: 'cg', name: 'República del Congo' },
  { id: 'cd', name: 'República Democrática del Congo' },
  { id: 'do', name: 'República Dominicana' },
  { id: 'rw', name: 'Ruanda' },
  { id: 'ro', name: 'Rumania' },
  { id: 'ru', name: 'Rusia' },
  { id: 'ws', name: 'Samoa' },
  { id: 'kn', name: 'San Cristóbal y Nieves' },
  { id: 'sm', name: 'San Marino' },
  { id: 'vc', name: 'San Vicente y las Granadinas' },
  { id: 'lc', name: 'Santa Lucía' },
  { id: 'st', name: 'Santo Tomé y Príncipe' },
  { id: 'sn', name: 'Senegal' },
  { id: 'rs', name: 'Serbia' },
  { id: 'sc', name: 'Seychelles' },
  { id: 'sl', name: 'Sierra Leona' },
  { id: 'sg', name: 'Singapur' },
  { id: 'sy', name: 'Siria' },
  { id: 'so', name: 'Somalia' },
  { id: 'lk', name: 'Sri Lanka' },
  { id: 'sd', name: 'Sudán' },
  { id: 'ss', name: 'Sudán del Sur' },
  { id: 'se', name: 'Suecia' },
  { id: 'ch', name: 'Suiza' },
  { id: 'sr', name: 'Surinam' },
  { id: 'th', name: 'Tailandia' },
  { id: 'tz', name: 'Tanzania' },
  { id: 'tj', name: 'Tayikistán' },
  { id: 'tl', name: 'Timor Oriental' },
  { id: 'tg', name: 'Togo' },
  { id: 'to', name: 'Tonga' },
  { id: 'tt', name: 'Trinidad y Tobago' },
  { id: 'tn', name: 'Túnez' },
  { id: 'tm', name: 'Turkmenistán' },
  { id: 'tr', name: 'Turquía' },
  { id: 'tv', name: 'Tuvalu' },
  { id: 'ua', name: 'Ucrania' },
  { id: 'ug', name: 'Uganda' },
  { id: 'uy', name: 'Uruguay' },
  { id: 'uz', name: 'Uzbekistán' },
  { id: 'vu', name: 'Vanuatu' },
  { id: 'va', name: 'Vaticano' },
  { id: 've', name: 'Venezuela' },
  { id: 'vn', name: 'Vietnam' },
  { id: 'ye', name: 'Yemen' },
  { id: 'dj', name: 'Yibuti' },
  { id: 'zm', name: 'Zambia' },
  { id: 'zw', name: 'Zimbabue' },
]

export function getCountryByName(name: string): Country | undefined {
  return COUNTRIES.find((country) => country.name === name)
}

export function getCountryById(id: string): Country | undefined {
  return COUNTRIES.find((country) => country.id === id)
}
